"""Puertos (interfaces) del inventario, pedidos y auth. Devuelven/aceptan
entidades de dominio."""
from typing import Protocol

from src.domain.entities import Categoria, Cliente, DetallePedido, Negocio, Pedido, PlantillaIa, Producto, Usuario


class CategoriaRepository(Protocol):
    def listar(self, negocio_id: str) -> list[Categoria]: ...
    def obtener(self, cat_id: str, negocio_id: str) -> Categoria | None: ...
    def agregar(self, categoria: Categoria, negocio_id: str) -> None: ...
    def actualizar(self, categoria: Categoria, negocio_id: str) -> None: ...
    def eliminar(self, cat_id: str, negocio_id: str) -> None: ...
    def reemplazar_todas(self, categorias: list[Categoria], negocio_id: str) -> None: ...


class ProductoRepository(Protocol):
    def listar(self, negocio_id: str) -> list[Producto]: ...
    def obtener(self, prod_id: str, negocio_id: str) -> Producto | None: ...
    def agregar(self, producto: Producto, negocio_id: str) -> None: ...
    def actualizar(self, producto: Producto, negocio_id: str) -> None: ...
    def eliminar(self, prod_id: str, negocio_id: str) -> None: ...
    def hay_en_categoria(self, cat_id: str, negocio_id: str) -> bool: ...
    def descontar_stock(self, items: list[dict], negocio_id: str) -> None: ...
    def reemplazar_todos(self, productos: list[Producto], negocio_id: str) -> None: ...


# ─── Pedidos ──────────────────────────────────────────────────────────────────

class ClienteRepository(Protocol):
    def upsert(self, nombre: str, numero_whatsapp: str, negocio_id: str) -> Cliente: ...


class NotificadorPedidos(Protocol):
    def notificar_cambio_estado(self, chat_id: str, pedido_id: str, estado: str) -> None: ...


class PedidoRepository(Protocol):
    def listar(self, negocio_id: str) -> list[Pedido]: ...
    def obtener(self, pedido_id: str, negocio_id: str) -> Pedido | None: ...
    def crear(self, cliente: Cliente, items: list[dict], datos: dict, negocio_id: str) -> Pedido: ...
    def cambiar_estado(self, pedido_id: str, estado: str, negocio_id: str) -> Pedido | None: ...
    def eliminar(self, pedido_id: str, negocio_id: str) -> bool: ...


# ─── Auth ─────────────────────────────────────────────────────────────────────

class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hash: str) -> bool: ...


class TokenService(Protocol):
    def emitir(self, usuario: Usuario) -> str: ...


class UsuarioRepository(Protocol):
    def por_email(self, email: str) -> tuple[Usuario, str] | None: ...  # (usuario, contrasena_hash)
    def crear(self, datos: dict, contrasena_hash: str, negocio_id: str) -> Usuario: ...  # raise EmailDuplicadoError on conflict
    def listar(self, negocio_id: str) -> list[Usuario]: ...
    def actualizar(self, usuario_id: str, datos: dict, negocio_id: str) -> Usuario | None: ...
    def eliminar(self, usuario_id: str, negocio_id: str) -> bool: ...


class NegocioRepository(Protocol):
    def crear(self, nombre: str) -> str: ...  # crea negocio con id nuevo, devuelve negocio_id
    def obtener(self, negocio_id: str) -> Negocio | None: ...
    def actualizar(self, datos: dict, negocio_id: str) -> Negocio: ...  # crea si no existe


class PlantillaIaRepository(Protocol):
    def obtener(self, negocio_id: str) -> PlantillaIa | None: ...
    def actualizar(self, datos: dict, negocio_id: str) -> PlantillaIa: ...  # upsert
