"""Puertos (interfaces) del inventario. Devuelven/aceptan entidades de dominio."""
from typing import Protocol

from src.domain.entities import Categoria, Producto


class CategoriaRepository(Protocol):
    def listar(self, negocio_id: str) -> list[Categoria]: ...
    def obtener(self, cat_id: str, negocio_id: str) -> Categoria | None: ...
    def agregar(self, categoria: Categoria, negocio_id: str) -> None: ...
    def actualizar(self, categoria: Categoria, negocio_id: str) -> None: ...
    def eliminar(self, cat_id: str, negocio_id: str) -> None: ...
    def reemplazar_todas(self, categorias: list[Categoria], negocio_id: str) -> None: ...


class ProductoRepository(Protocol):
    def listar(self, negocio_id: str) -> list[Producto]: ...
    def obtener(self, prod_id: str, negocio_id: str) -> Producto | None: ...
    def agregar(self, producto: Producto, negocio_id: str) -> None: ...
    def actualizar(self, producto: Producto, negocio_id: str) -> None: ...
    def eliminar(self, prod_id: str, negocio_id: str) -> None: ...
    def hay_en_categoria(self, cat_id: str, negocio_id: str) -> bool: ...
    def descontar_stock(self, items: list[dict], negocio_id: str) -> None: ...
    def reemplazar_todos(self, productos: list[Producto], negocio_id: str) -> None: ...
